"""add environmental models

Revision ID: 1234567890ab
Revises: ab26349579f9
Create Date: 2026-07-12 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '1234567890ab'
down_revision: Union[str, Sequence[str], None] = 'ab26349579f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    
    op.create_table('facilities',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_id'), 'facilities', ['id'], unique=False)

    op.create_table('carbon_emissions',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('scope', sa.Enum('scope_1', 'scope_2', 'scope_3', name='scopeenum'), nullable=False),
    sa.Column('value_tco2e', sa.Float(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carbon_emissions_company_id'), 'carbon_emissions', ['company_id'], unique=False)
    op.create_index(op.f('ix_carbon_emissions_date'), 'carbon_emissions', ['date'], unique=False)
    op.create_index(op.f('ix_carbon_emissions_id'), 'carbon_emissions', ['id'], unique=False)
    op.create_index(op.f('ix_carbon_emissions_scope'), 'carbon_emissions', ['scope'], unique=False)

    op.create_table('energy_usage',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('energy_type', sa.Enum('electricity', 'gas', 'renewable', 'other', name='energytypeenum'), nullable=False),
    sa.Column('kwh_consumed', sa.Float(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_usage_date'), 'energy_usage', ['date'], unique=False)
    op.create_index(op.f('ix_energy_usage_energy_type'), 'energy_usage', ['energy_type'], unique=False)
    op.create_index(op.f('ix_energy_usage_facility_id'), 'energy_usage', ['facility_id'], unique=False)
    op.create_index(op.f('ix_energy_usage_id'), 'energy_usage', ['id'], unique=False)

    op.create_table('waste_tracking',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('waste_type', sa.Enum('recycled', 'landfill', 'composted', 'hazardous', name='wastetypeenum'), nullable=False),
    sa.Column('kg_recycled', sa.Float(), nullable=False),
    sa.Column('kg_landfill', sa.Float(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waste_tracking_company_id'), 'waste_tracking', ['company_id'], unique=False)
    op.create_index(op.f('ix_waste_tracking_date'), 'waste_tracking', ['date'], unique=False)
    op.create_index(op.f('ix_waste_tracking_id'), 'waste_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_waste_tracking_waste_type'), 'waste_tracking', ['waste_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waste_tracking_waste_type'), table_name='waste_tracking')
    op.drop_index(op.f('ix_waste_tracking_id'), table_name='waste_tracking')
    op.drop_index(op.f('ix_waste_tracking_date'), table_name='waste_tracking')
    op.drop_index(op.f('ix_waste_tracking_company_id'), table_name='waste_tracking')
    op.drop_table('waste_tracking')
    
    op.drop_index(op.f('ix_energy_usage_id'), table_name='energy_usage')
    op.drop_index(op.f('ix_energy_usage_facility_id'), table_name='energy_usage')
    op.drop_index(op.f('ix_energy_usage_energy_type'), table_name='energy_usage')
    op.drop_index(op.f('ix_energy_usage_date'), table_name='energy_usage')
    op.drop_table('energy_usage')
    
    op.drop_index(op.f('ix_carbon_emissions_scope'), table_name='carbon_emissions')
    op.drop_index(op.f('ix_carbon_emissions_id'), table_name='carbon_emissions')
    op.drop_index(op.f('ix_carbon_emissions_date'), table_name='carbon_emissions')
    op.drop_index(op.f('ix_carbon_emissions_company_id'), table_name='carbon_emissions')
    op.drop_table('carbon_emissions')
    
    op.drop_index(op.f('ix_facilities_id'), table_name='facilities')
    op.drop_table('facilities')
    
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    
    sa.Enum(name='scopeenum').drop(op.get_bind())
    sa.Enum(name='energytypeenum').drop(op.get_bind())
    sa.Enum(name='wastetypeenum').drop(op.get_bind())
    # ### end Alembic commands ###
