"""add governance models

Revision ID: 2345678901bc
Revises: 1234567890ab
Create Date: 2026-07-12 13:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '2345678901bc'
down_revision: Union[str, Sequence[str], None] = '1234567890ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='policystatusenum'), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_effective_date'), 'policies', ['effective_date'], unique=False)
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_index(op.f('ix_policies_owner_id'), 'policies', ['owner_id'], unique=False)

    op.create_table('compliance_audits',
    sa.Column('audit_date', sa.Date(), nullable=False),
    sa.Column('auditor_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('findings', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_audits_audit_date'), 'compliance_audits', ['audit_date'], unique=False)
    op.create_index(op.f('ix_compliance_audits_auditor_id'), 'compliance_audits', ['auditor_id'], unique=False)
    op.create_index(op.f('ix_compliance_audits_id'), 'compliance_audits', ['id'], unique=False)

    op.create_table('board_activities',
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_activities_id'), 'board_activities', ['id'], unique=False)
    op.create_index(op.f('ix_board_activities_meeting_date'), 'board_activities', ['meeting_date'], unique=False)

    op.create_table('board_activity_attendees',
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['board_activities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('activity_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_activity_attendees')
    
    op.drop_index(op.f('ix_board_activities_meeting_date'), table_name='board_activities')
    op.drop_index(op.f('ix_board_activities_id'), table_name='board_activities')
    op.drop_table('board_activities')
    
    op.drop_index(op.f('ix_compliance_audits_id'), table_name='compliance_audits')
    op.drop_index(op.f('ix_compliance_audits_auditor_id'), table_name='compliance_audits')
    op.drop_index(op.f('ix_compliance_audits_audit_date'), table_name='compliance_audits')
    op.drop_table('compliance_audits')
    
    op.drop_index(op.f('ix_policies_owner_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_effective_date'), table_name='policies')
    op.drop_table('policies')
    
    sa.Enum(name='policystatusenum').drop(op.get_bind())
    # ### end Alembic commands ###
