"""Sync models with master

Revision ID: 2f9eb8066901
Revises: a1b2c3d4e5f7
Create Date: 2026-07-12 22:41:50.449940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f9eb8066901'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('csr_activity', 'challenge', name='categorytypeenum'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='categorystatusenum'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('emission_factors',
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('co2_factor_value', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emission_factors_id'), 'emission_factors', ['id'], unique=False)
    op.create_table('rewards',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('points_required', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'out_of_stock', 'retired', name='rewardstatusenum'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rewards_id'), 'rewards', ['id'], unique=False)
    op.create_table('challenges',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='challengedifficultyenum'), nullable=False),
    sa.Column('evidence_required', sa.Boolean(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'under_review', 'completed', 'archived', name='challengestatusenum'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_id'), 'challenges', ['id'], unique=False)
    op.create_table('product_esg_profiles',
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_ref', sa.String(length=100), nullable=True),
    sa.Column('emission_factor_id', sa.UUID(), nullable=True),
    sa.Column('esg_notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['emission_factor_id'], ['emission_factors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_esg_profiles_id'), 'product_esg_profiles', ['id'], unique=False)
    op.create_table('audits',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('auditor_id', sa.UUID(), nullable=False),
    sa.Column('audit_date', sa.Date(), nullable=False),
    sa.Column('findings', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'completed', name='auditstatusenum'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audits_audit_date'), 'audits', ['audit_date'], unique=False)
    op.create_index(op.f('ix_audits_auditor_id'), 'audits', ['auditor_id'], unique=False)
    op.create_index(op.f('ix_audits_id'), 'audits', ['id'], unique=False)
    op.create_table('carbon_transactions',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source_type', sa.Enum('purchase', 'manufacturing', 'expense', 'fleet', name='carbonsourcetypeenum'), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('emission_factor_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('calculated_co2e', sa.Float(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('auto_generated', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['emission_factor_id'], ['emission_factors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carbon_transactions_date'), 'carbon_transactions', ['date'], unique=False)
    op.create_index(op.f('ix_carbon_transactions_id'), 'carbon_transactions', ['id'], unique=False)
    op.create_table('challenge_participations',
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('proof', sa.String(length=1000), nullable=True),
    sa.Column('approval', sa.Enum('pending', 'approved', 'rejected', name='challengeapprovalenum'), nullable=True),
    sa.Column('xp_awarded', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_participations_id'), 'challenge_participations', ['id'], unique=False)
    op.create_table('csr_activities',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('evidence_required', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'active', 'completed', name='csrstatusenum'), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csr_activities_id'), 'csr_activities', ['id'], unique=False)
    op.create_index(op.f('ix_csr_activities_start_date'), 'csr_activities', ['start_date'], unique=False)
    op.create_index(op.f('ix_csr_activities_status'), 'csr_activities', ['status'], unique=False)
    op.create_table('department_scores',
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('environmental_score', sa.Float(), nullable=False),
    sa.Column('social_score', sa.Float(), nullable=False),
    sa.Column('governance_score', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_scores_department_id'), 'department_scores', ['department_id'], unique=False)
    op.create_index(op.f('ix_department_scores_id'), 'department_scores', ['id'], unique=False)
    op.create_index(op.f('ix_department_scores_period'), 'department_scores', ['period'], unique=False)
    op.create_table('environmental_goals',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('target_co2', sa.Float(), nullable=False),
    sa.Column('current_co2', sa.Float(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'on_track', 'at_risk', 'completed', name='environmentalgoalstatusenum'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environmental_goals_id'), 'environmental_goals', ['id'], unique=False)
    op.create_table('policy_acknowledgements',
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('acknowledged_at', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_acknowledgements_id'), 'policy_acknowledgements', ['id'], unique=False)
    op.create_table('compliance_issues',
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='complianceissueseverityenum'), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', name='complianceissuestatusenum'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_issues_id'), 'compliance_issues', ['id'], unique=False)
    op.create_table('employee_participations',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('proof', sa.String(length=1000), nullable=True),
    sa.Column('approval_status', sa.Enum('pending', 'approved', 'rejected', name='employeeparticipationapprovalenum'), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['csr_activities.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_participations_id'), 'employee_participations', ['id'], unique=False)
    op.drop_index(op.f('ix_compliance_audits_audit_date'), table_name='compliance_audits')
    op.drop_index(op.f('ix_compliance_audits_auditor_id'), table_name='compliance_audits')
    op.drop_index(op.f('ix_compliance_audits_id'), table_name='compliance_audits')
    op.drop_table('compliance_audits')
    op.drop_index(op.f('ix_employees_company_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_csr_initiatives_id'), table_name='csr_initiatives')
    op.drop_index(op.f('ix_csr_initiatives_responsible_id'), table_name='csr_initiatives')
    op.drop_index(op.f('ix_csr_initiatives_start_date'), table_name='csr_initiatives')
    op.drop_index(op.f('ix_csr_initiatives_status'), table_name='csr_initiatives')
    op.drop_table('csr_initiatives')
    op.add_column('badges', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('badges', sa.Column('unlock_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.alter_column('badges', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('badges', 'criteria')
    op.drop_column('badges', 'points_value')
    op.alter_column('board_activities', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('board_activity_attendees', 'activity_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('board_activity_attendees', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('carbon_emissions', 'company_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('carbon_emissions', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('companies', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('company_settings', sa.Column('auto_emission_calculation', sa.Boolean(), nullable=True))
    op.add_column('company_settings', sa.Column('require_evidence_csr', sa.Boolean(), nullable=True))
    op.add_column('company_settings', sa.Column('auto_award_badges', sa.Boolean(), nullable=True))
    op.add_column('company_settings', sa.Column('email_alerts_compliance', sa.Boolean(), nullable=True))
    op.add_column('company_settings', sa.Column('weight_environmental', sa.Float(), nullable=True))
    op.add_column('company_settings', sa.Column('weight_social', sa.Float(), nullable=True))
    op.add_column('company_settings', sa.Column('weight_governance', sa.Float(), nullable=True))
    op.alter_column('company_settings', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('departments', sa.Column('code', sa.String(length=50), nullable=True))
    op.add_column('departments', sa.Column('head_id', sa.UUID(), nullable=True))
    op.add_column('departments', sa.Column('parent_department_id', sa.UUID(), nullable=True))
    op.add_column('departments', sa.Column('employee_count', sa.Integer(), nullable=True))
    op.add_column('departments', sa.Column('status', sa.Enum('active', 'inactive', name='departmentstatusenum'), nullable=True))
    op.alter_column('departments', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_foreign_key(None, 'departments', 'departments', ['parent_department_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'departments', 'users', ['head_id'], ['id'], ondelete='SET NULL')
    op.alter_column('diversity_metrics', 'department_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('diversity_metrics', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('employee_wellbeing', 'employee_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('employee_wellbeing', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint(None, 'employee_wellbeing', type_='foreignkey')
    op.create_foreign_key(None, 'employee_wellbeing', 'users', ['employee_id'], ['id'], ondelete='CASCADE')
    op.alter_column('energy_usage', 'facility_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('energy_usage', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('esg_score_summaries', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('facilities', 'company_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('facilities', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('notifications', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.alter_column('points_ledgers', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('points_ledgers', 'source_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('points_ledgers', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('policies', 'owner_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('policies', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('waste_tracking', 'company_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('waste_tracking', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waste_tracking', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('waste_tracking', 'company_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('policies', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('policies', 'owner_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('points_ledgers', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('points_ledgers', 'source_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('points_ledgers', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.alter_column('notifications', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('facilities', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('facilities', 'company_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('esg_score_summaries', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('energy_usage', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('energy_usage', 'facility_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_constraint(None, 'employee_wellbeing', type_='foreignkey')
    op.create_foreign_key(None, 'employee_wellbeing', 'employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.alter_column('employee_wellbeing', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('employee_wellbeing', 'employee_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('diversity_metrics', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('diversity_metrics', 'department_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.alter_column('departments', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('departments', 'status')
    op.drop_column('departments', 'employee_count')
    op.drop_column('departments', 'parent_department_id')
    op.drop_column('departments', 'head_id')
    op.drop_column('departments', 'code')
    op.alter_column('company_settings', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('company_settings', 'weight_governance')
    op.drop_column('company_settings', 'weight_social')
    op.drop_column('company_settings', 'weight_environmental')
    op.drop_column('company_settings', 'email_alerts_compliance')
    op.drop_column('company_settings', 'auto_award_badges')
    op.drop_column('company_settings', 'require_evidence_csr')
    op.drop_column('company_settings', 'auto_emission_calculation')
    op.alter_column('companies', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('carbon_emissions', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('carbon_emissions', 'company_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('board_activity_attendees', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('board_activity_attendees', 'activity_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('board_activities', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.add_column('badges', sa.Column('points_value', sa.INTEGER(), nullable=False))
    op.add_column('badges', sa.Column('criteria', sa.TEXT(), nullable=False))
    op.alter_column('badges', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('badges', 'unlock_rule')
    op.drop_column('badges', 'description')
    op.create_table('csr_initiatives',
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('budget', sa.NUMERIC(precision=14, scale=2), nullable=False),
    sa.Column('beneficiaries', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('responsible_id', sa.NUMERIC(), nullable=True),
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csr_initiatives_status'), 'csr_initiatives', ['status'], unique=False)
    op.create_index(op.f('ix_csr_initiatives_start_date'), 'csr_initiatives', ['start_date'], unique=False)
    op.create_index(op.f('ix_csr_initiatives_responsible_id'), 'csr_initiatives', ['responsible_id'], unique=False)
    op.create_index(op.f('ix_csr_initiatives_id'), 'csr_initiatives', ['id'], unique=False)
    op.create_table('employees',
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('department_id', sa.NUMERIC(), nullable=True),
    sa.Column('company_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_company_id'), 'employees', ['company_id'], unique=False)
    op.create_table('compliance_audits',
    sa.Column('audit_date', sa.DATE(), nullable=False),
    sa.Column('auditor_id', sa.NUMERIC(), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.Column('findings', sa.TEXT(), nullable=False),
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_audits_id'), 'compliance_audits', ['id'], unique=False)
    op.create_index(op.f('ix_compliance_audits_auditor_id'), 'compliance_audits', ['auditor_id'], unique=False)
    op.create_index(op.f('ix_compliance_audits_audit_date'), 'compliance_audits', ['audit_date'], unique=False)
    op.drop_index(op.f('ix_employee_participations_id'), table_name='employee_participations')
    op.drop_table('employee_participations')
    op.drop_index(op.f('ix_compliance_issues_id'), table_name='compliance_issues')
    op.drop_table('compliance_issues')
    op.drop_index(op.f('ix_policy_acknowledgements_id'), table_name='policy_acknowledgements')
    op.drop_table('policy_acknowledgements')
    op.drop_index(op.f('ix_environmental_goals_id'), table_name='environmental_goals')
    op.drop_table('environmental_goals')
    op.drop_index(op.f('ix_department_scores_period'), table_name='department_scores')
    op.drop_index(op.f('ix_department_scores_id'), table_name='department_scores')
    op.drop_index(op.f('ix_department_scores_department_id'), table_name='department_scores')
    op.drop_table('department_scores')
    op.drop_index(op.f('ix_csr_activities_status'), table_name='csr_activities')
    op.drop_index(op.f('ix_csr_activities_start_date'), table_name='csr_activities')
    op.drop_index(op.f('ix_csr_activities_id'), table_name='csr_activities')
    op.drop_table('csr_activities')
    op.drop_index(op.f('ix_challenge_participations_id'), table_name='challenge_participations')
    op.drop_table('challenge_participations')
    op.drop_index(op.f('ix_carbon_transactions_id'), table_name='carbon_transactions')
    op.drop_index(op.f('ix_carbon_transactions_date'), table_name='carbon_transactions')
    op.drop_table('carbon_transactions')
    op.drop_index(op.f('ix_audits_id'), table_name='audits')
    op.drop_index(op.f('ix_audits_auditor_id'), table_name='audits')
    op.drop_index(op.f('ix_audits_audit_date'), table_name='audits')
    op.drop_table('audits')
    op.drop_index(op.f('ix_product_esg_profiles_id'), table_name='product_esg_profiles')
    op.drop_table('product_esg_profiles')
    op.drop_index(op.f('ix_challenges_id'), table_name='challenges')
    op.drop_table('challenges')
    op.drop_index(op.f('ix_rewards_id'), table_name='rewards')
    op.drop_table('rewards')
    op.drop_index(op.f('ix_emission_factors_id'), table_name='emission_factors')
    op.drop_table('emission_factors')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
