"""initial revision

Revision ID: ab26349579f9
Revises: 
Create Date: 2026-07-12 11:35:17.861055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab26349579f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_settings',
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('carbon_target', sa.Float(), nullable=False),
    sa.Column('water_target', sa.Float(), nullable=False),
    sa.Column('waste_target', sa.Float(), nullable=False),
    sa.Column('diversity_target', sa.Float(), nullable=False),
    sa.Column('governance_target', sa.Float(), nullable=False),
    sa.Column('low_score_threshold', sa.Float(), nullable=False),
    sa.Column('medium_score_threshold', sa.Float(), nullable=False),
    sa.Column('notification_email_alerts', sa.Boolean(), nullable=False),
    sa.Column('notification_weekly_reports', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_settings_id'), 'company_settings', ['id'], unique=False)
    op.create_table('esg_score_summaries',
    sa.Column('company_id', sa.String(length=100), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('environmental_score', sa.Float(), nullable=False),
    sa.Column('social_score', sa.Float(), nullable=False),
    sa.Column('governance_score', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_esg_score_summaries_company_id'), 'esg_score_summaries', ['company_id'], unique=False)
    op.create_index(op.f('ix_esg_score_summaries_id'), 'esg_score_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_esg_score_summaries_period'), 'esg_score_summaries', ['period'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'esg_manager', 'environmental_officer', 'social_officer', 'governance_officer', 'employee', name='user_role_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('points_ledgers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('source_table', sa.String(length=100), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_ledgers_id'), 'points_ledgers', ['id'], unique=False)
    op.create_index(op.f('ix_points_ledgers_user_id'), 'points_ledgers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_points_ledgers_user_id'), table_name='points_ledgers')
    op.drop_index(op.f('ix_points_ledgers_id'), table_name='points_ledgers')
    op.drop_table('points_ledgers')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_esg_score_summaries_period'), table_name='esg_score_summaries')
    op.drop_index(op.f('ix_esg_score_summaries_id'), table_name='esg_score_summaries')
    op.drop_index(op.f('ix_esg_score_summaries_company_id'), table_name='esg_score_summaries')
    op.drop_table('esg_score_summaries')
    op.drop_index(op.f('ix_company_settings_id'), table_name='company_settings')
    op.drop_table('company_settings')
    # ### end Alembic commands ###
